### PR TITLE
Some stuff I've done without checking anything in

### PR DESCRIPTION
**Pull request by adyates**
Reviewer: A bunny

Make it happen boyz

[Review on Reviewable](https://reviewable.io/reviews/adyates/uyclass-cs253/1)

### CODE REVIEW

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[.settings/com.google.appengine.eclipse.core.prefs, line 6 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpBYaljXWcCMVFsDA)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/.settings/com.google.appengine.eclipse.core.prefs#L6)):</sup>
I have no idea what this line does

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[war/birth.jsp, line 12 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpJvaHb_Rsh1qvTYX)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/birth.jsp#L12)):</sup>
Hey did this ever work?

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

This is a test!

---

**Comment by pkaminski** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[.settings/com.google.appengine.eclipse.core.prefs, line 6 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpBYaljXWcCMVFsDA)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/.settings/com.google.appengine.eclipse.core.prefs#L6)):</sup>
Causes Eclipse to launch the GAE app in the browser?  'cause, y'know, otherwise it would just launch it in a shell, or out the window...

---

<sup>**[war/birth.jsp, line 12 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpJvaHb_Rsh1qvTYX)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/birth.jsp#L12)):</sup>
Sure did.

---

**Comment by pkaminski** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

Reviewed files:
- .classpath @ r1
- .settings/com.google.appengine.eclipse.core.prefs @ r1
- .settings/org.eclipse.php.core.prefs @ r1

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

LGTM mon frere

---

<sup>**[.classpath, line 5 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTreDxRHOFzyL2qHHH)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/.classpath#L5)):</sup>
There wasn't a change here.  I'm just being goofy as hell.

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[war/WEB-INF/lib/appengine-jsr107cache-1.8.4.jar, line 0 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTs5oXEkMUQ41iUjHk)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/WEB-INF/lib/appengine-jsr107cache-1.8.4.jar#L0)):</sup>
I don't line binaries.  Unjar it first.

---

<sup>**[war/jsp/welcome.jsp, line 1 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTsBiMadJ8SPF_L-Vr)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/jsp/welcome.jsp#L1)):</sup>
You should change this to show more green text

---

**Comment by pkaminski** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[war/WEB-INF/lib/appengine-jsr107cache-1.8.4.jar, line 0 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTs5oXEkMUQ41iUjHk)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/WEB-INF/lib/appengine-jsr107cache-1.8.4.jar#L0)):</sup>
That would make a fine mess...

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[.settings/com.google.appengine.eclipse.core.prefs, line 6 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpBYaljXWcCMVFsDA)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/.settings/com.google.appengine.eclipse.core.prefs#L6)):</sup>
Done.

---

<sup>**[war/jsp/welcome.jsp, line 22 [r2]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTsnhsZdrVAWXXU6u6)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/86c81726cabe854ac0f85ee1f57b819fac62e69c/war/jsp/welcome.jsp#L22)):</sup>
That's right.  Remove that mess!

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

<sup>**[war/birth.jsp, line 12 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpJvaHb_Rsh1qvTYX)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/birth.jsp#L12)):</sup>
Actually it didn't =(

---

**Comment by adyates** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

---

I'm just discussing from here

---

**Comment by pkaminski** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

Reviewed files:
- war/WEB-INF/lib/appengine-api-1.0-sdk-1.6.5.jar @ r1
- war/WEB-INF/lib/appengine-api-1.0-sdk-1.8.4.jar @ r1
- war/WEB-INF/lib/appengine-api-labs-1.6.5.jar @ r1
- war/WEB-INF/lib/appengine-api-labs.jar @ r1
- war/WEB-INF/lib/appengine-endpoints.jar @ r1
- war/WEB-INF/lib/appengine-jsr107cache-1.6.5.jar @ r1
- war/WEB-INF/lib/appengine-jsr107cache-1.8.4.jar @ r1
- war/birth.jsp @ r1
- war/jsp/welcome.jsp @ r1

---

<sup>**[war/birth.jsp, line 12 [r1]](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1#-JWTpJvaHb_Rsh1qvTYX)** ([raw file](https://github.com/adyates/uyclass-cs253/blob/99a9d1b29467789d127d3927980364e02a6f419c/war/birth.jsp#L12)):</sup>
Then fix it!

---

**Comment by adyates** [comment]
Eh

---

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

**Comment by adyates** [comment]
Reviewed files:
- war/birth.jsp @ r3
- war/jsp/welcome.jsp @ r2

---

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/adyates/uyclass-cs253/1)

**Pull request merged**
